<?php

/**
 * Dump the current SQLite schema to db/schema.sql.
 *
 * The committed db/schema.sql lets a fresh environment rebuild the database
 * structure from scratch (the live db/tarotdb.db is gitignored). Re-run this
 * after applying a migration so the committed schema stays in sync.
 *
 * Usage (from the project root):
 *   php scripts/dump_schema.php
 *
 * Rebuild a fresh database from the dump:
 *   sqlite3 db/tarotdb.db < db/schema.sql
 */

require_once __DIR__ . '/../vendor/autoload.php';

use Tarot\Database\Connection;

$pdo = Connection::getInstance();

$rows = $pdo->query(
    'SELECT type, name, sql FROM sqlite_master
     WHERE sql IS NOT NULL AND name NOT LIKE "sqlite_%"
     ORDER BY CASE type WHEN "table" THEN 1 WHEN "index" THEN 2 WHEN "trigger" THEN 3 ELSE 4 END, name'
)->fetchAll(PDO::FETCH_ASSOC);

$out  = "-- TarotGen.io database schema (SQLite).\n";
$out .= "-- Generated by scripts/dump_schema.php — do not edit by hand.\n";
$out .= "-- Rebuild a fresh DB:  sqlite3 db/tarotdb.db < db/schema.sql\n\n";
$out .= "PRAGMA foreign_keys = ON;\n";

foreach ($rows as $row) {
    $out .= "\n" . trim((string)$row['sql']) . ";\n";
}

$target = __DIR__ . '/../db/schema.sql';
file_put_contents($target, $out);

echo 'Wrote ' . count($rows) . " schema objects to db/schema.sql\n";
